version: '3.7'
services:
  scrapy:
    build:
      context: .
    entrypoint:
      - scrapy
    volumes:
      - ./mtgo_decklist_scraper:/mtgo_decklist_scraper:ro
      - ./scrapy.cfg:/scrapy.cfg:ro
      - ./outputs:/outputs
      - ./httpcache:/.scrapy/httpcache
